Repository UMC-7th-Peekle/peekle-frontend, pull requests merged in 2025-02, with the labels that each got.

#71 [✨ Feature] 커뮤니티 페이지 UI 제작
  .yarn/install-state.gz
  src/assets/images/community/camera.svg
  src/assets/images/community/check.svg
  src/components/community/anonymous-check/index.tsx
  src/components/community/anonymous-check/style.ts
  src/components/index.ts
  src/pages/community/edit/index.tsx
  src/pages/community/edit/style.ts
  yarn.lock
Labels: ✨ Feature

#76 [🔄 Refactor] 이벤트 리팩토링
  .yarn/install-state.gz
  index.html
  src/assets/images/event/card/mapButton.svg
  src/components/common/deferred-loader/index.tsx
  src/components/common/information/bottom-sheet/index.tsx
  src/components/common/information/bottom-sheet/style.ts
  src/components/common/information/portal/index.tsx
  src/components/event/category-chips/index.tsx
  src/components/event/event-map/index.tsx
  src/components/event/event-map/style.ts
  src/components/event/location-confirm/index.tsx
  src/constants/event.ts
  src/hooks/event/useEventFilter.ts
  src/hooks/event/useMapCluster.ts
  src/hooks/event/useMapMarkers.ts
  src/hooks/index.ts
  src/pages/event/[id]/index.tsx
  src/pages/event/[id]/style.ts
  src/pages/event/hooks/mutation/useDeleteScrapEvent.ts
  src/pages/event/hooks/mutation/usePostScrapEvent.ts
  src/pages/event/map/index.tsx
  src/pages/event/map/style.ts
  src/sample-data/event.ts
  src/stores/event/useMapStore.ts
  src/stores/event/useMyLocationStore.ts
  src/types/event.ts
  src/utils/MarkerClustering.ts
  src/utils/eventFormatter.ts
  src/utils/getMarker.ts
Labels: 🔄 Refactor

#86 [✨ Feature] 이벤트 공유 동적 메타태그, 카카오톡 공유하기
  .yarn/install-state.gz
  index.html
  package.json
  src/components/common/meta-tag/index.tsx
  src/constants/common.ts
  src/pages/event/[id]/index.tsx
  src/pages/event/hooks/query/useGetEventDetail.ts
  src/pages/event/hooks/useShareKakao.ts
  src/types/common.ts
  src/types/global.d.ts
  src/types/kakao.d.ts
  src/utils/getBaseUrl.ts
  src/utils/getSubstring.ts
  src/utils/index.ts
  tsconfig.node.json
  yarn.lock
Labels: ✨ Feature

#89 [🚑 Hotfix] 카카오톡 공유 4019 오류 해결
  src/pages/event/hooks/useShareKakao.ts
  src/utils/getSubstring.ts
Labels: 🚑 Hotfix

#102 [🔧 Fix] 이벤트 오류 수정
  package.json
  src/App.tsx
  src/components/common/deferred-loader/index.tsx
  src/components/event/card/index.tsx
  src/components/event/event-map-container/index.tsx
  src/components/event/event-map/index.tsx
  src/components/event/list/index.tsx
  src/hooks/common/useRecentSearch.ts
  src/hooks/event/query/useGetEvents.ts
  src/pages/onboarding/index.tsx
  src/stores/common/useRecentSearchStore.ts
  src/stores/index.ts
  src/utils/error.ts
Labels: 🔧 Fix
