Repository UMC-7th-Peekle/peekle-frontend, pull requests merged in 2025-01, with the labels that each got.

#3 [⚙️ Chore] 프로젝트 초기 설정 (auto assign, eslint, prettier, husky)
  .commitlintrc.json
  .github/ISSUE_TEMPLATE/fix.yml
  .github/ISSUE_TEMPLATE/hotfix.yml
  .github/auto_assign.yml
  .github/workflows/action.yml
  .husky/commit-msg
  .husky/pre-commit
  .husky/pre-push
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/index.css
  src/layouts/Layout.tsx
  src/main.tsx
  src/route/outlet.tsx
  src/route/route.tsx
  src/routes/Router.tsx
  src/styles/GlobalStyles.tsx
  src/styles/designToken.css
  src/styles/fonts.css
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: ⚙ chore

#23 [✨ Feature] Input 컴포넌트 제작
  .yarn/install-state.gz
  package.json
  src/assets/images/icons/map.svg
  src/assets/images/icons/plus.svg
  src/components/calendar/index.tsx
  src/components/calendar/store.ts
  src/components/calendar/style.ts
  src/components/input/Checkbox/index.tsx
  src/components/input/Checkbox/style.ts
  src/components/input/CheckboxCard/index.tsx
  src/components/input/CheckboxCard/style.ts
  src/components/input/DateList/index.tsx
  src/components/input/DateList/style.ts
  src/components/input/Radio/index.tsx
  src/components/input/Radio/style.ts
  src/components/input/TextFields/index.tsx
  src/components/input/TextFields/style.ts
  src/components/input/TextFields/useTextFields.ts
  src/components/input/TextFields/utils.ts
  src/layouts/SearchBar/index.tsx
  src/layouts/SearchBar/style.ts
  src/pages/TestPage/CalendarPage.tsx
  src/pages/TestPage/InputComponentsPage.tsx
  src/pages/TestPage/SearchBarPage.tsx
  src/routes/Router.tsx
  src/utils/date/formatDate.ts
  src/utils/date/isInRange.ts
  src/utils/date/isSameDay.ts
  vite.config.ts
  yarn.lock
Labels: ✨ Feature

#38 [✨ Feature] 이벤트 페이지 공통 컴포넌트 적용
  index.html
  src/components/common/information/Portal/style.ts
  src/components/common/information/bottom-sheet/style.ts
  src/components/common/information/modal/Alert/style.ts
  src/components/common/information/modal/Confirm/style.ts
  src/components/common/input/dropdown/index.tsx
  src/components/common/input/text-fields/index.tsx
  src/components/common/input/text-fields/useTextFields.ts
  src/components/event/bottom-sheet-tabs/duration/index.tsx
  src/components/event/event-map/index.tsx
  src/components/event/event-map/style.ts
  src/components/event/filter-chip/index.tsx
  src/components/event/filter-chips/index.tsx
  src/components/event/list/index.tsx
  src/components/event/map-bottom-sheet/index.tsx
  src/components/event/map-bottom-sheet/style.ts
  src/components/index.ts
  src/constants/event.ts
  src/hooks/event/useEventFilter.ts
  src/layouts/navbar/style.ts
  src/layouts/search-bar/index.tsx
  src/pages/event/:id/index.tsx
  src/pages/event/index/index.tsx
  src/pages/event/index/style.ts
  src/pages/event/map/index.tsx
  src/pages/event/map/style.ts
  src/pages/event/search/index.tsx
  src/pages/event/search/style.ts
  src/types/event.ts
Labels: ✨ Feature

#40 [🐛 Bug] FilterChips 가로스크롤, bottomSheet nav 가리지 않게
  src/components/common/information/bottom-sheet/index.tsx
  src/components/common/information/bottom-sheet/style.ts
  src/components/event/filter-chips/style.ts
  src/components/event/map-bottom-sheet/style.ts
Labels: 🔧 Fix

#44 [🔧 Fix] 이벤트 상세 폴더 이름 변경
  src/pages/event/[id]/index.tsx
  src/pages/event/[id]/style.ts
  src/pages/index.ts
Labels: 🔧 Fix

#48 [✨ Feature] axios client, clientAuth 생성
  .gitignore
  .yarn/install-state.gz
  package.json
  src/apis/client.ts
  src/components/common/toggle-heart/index.tsx
  src/components/common/toggle-heart/style.ts
  src/components/community/edit-button/index.tsx
  src/components/community/edit-button/style.ts
  src/components/community/toggle-search/index.tsx
  src/components/community/toggle-search/style.ts
  src/components/index.ts
  src/constants/routes.ts
  src/hooks/usePeekleQuery.ts
  src/layouts/navbar/style.ts
  src/pages/community/const/mockupData.ts
  src/pages/community/container/body-section/index.tsx
  src/pages/community/container/body-section/style.ts
  src/pages/community/hooks/query/useGetCommunityId.ts
  src/pages/community/index.tsx
  src/pages/community/like/index.tsx
  src/pages/community/like/style.ts
  src/pages/community/page.tsx
  src/pages/community/search/index.tsx
  src/pages/community/search/style.ts
  src/pages/community/style.ts
  src/pages/index.ts
  src/routes/Router.tsx
  src/styles/GlobalStyles.ts
  src/styles/theme.ts
  yarn.lock
Labels: ✨ Feature

#59 [✨ Feature] favicon, link preview
  index.html
  public/favicon.svg
  public/preview-image.png
  public/vite.svg
Labels: ✨ Feature, 🖼 asset
